name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: "(cd tests && bash testexit.sh )"
      id: cd-tests-bash-testexit-sh
      uses: education/autograding-command-grader@v1
      with:
        test-name: "(cd tests && bash testexit.sh )"
        setup-command: ''
        command: "(cd tests && bash testexit.sh )"
        timeout: 1
        max-score: 15
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        CD-TESTS-BASH-TESTEXIT-SH_RESULTS: "${{steps.cd-tests-bash-testexit-sh.outputs.result}}"
      with:
        runners: cd-tests-bash-testexit-sh
